filebeat.inputs:
- type: log
  enabled: false
  paths:
    - /var/log/*.log

- type: filestream
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s
  tags: ["zeek"]

  #setup.kibana:

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false

  #output.logstash:
  #hosts: ["127.0.0.1:5044"]
  #bulk_max_size: 1024

setup.kibana:
  host: "192.168.66.99:5601"
  username: "elastic"
  password: "yourpass"

output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "elastic"
  password: "yourpass"
  pipeline: geoip-info

processors:
  add_host_metadata:
  when.not.contains.tags: forwarded
  add_cloud_metadata: ~
  add_docker_metadata: ~
  add_kubernetes_metadata: ~
